imageCredentials:
  create: false
  name: csp-registry-secret # When create is false please specify
  repositoryUriPrefix: "registry.aquasec.com" # for dockerhub - "docker.io"
  registry: "registry.aquasec.com" #REQUIRED only if create is true, for dockerhub - "index.docker.io/v1/"
  username: ""
  password: ""
  email:

enforcerToken: ""

rbac:
  enabled: false
  roleRef:

gate:
  host: csp-gateway-svc
  port: 3622

image:
  repository: enforcer
  tag: 3.5
  pullPolicy: IfNotPresent

livenessProbe: {}
readinessProbe: {}
nodeSelector: {}

resources:
  requests:
    memory: "150Mi"
    cpu: "30m"
  limits:
    memory: "300Mi"
    cpu: "60m"

tolerations: []
# - key: "key"
#   operator: "Equal|Exists"
#   value: "value"
#   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"
